import { Metadata } from "next";
import "./globals.css";
import { gilroy } from "./fonsts";

// Метаданные страницы
export const metadata: Metadata = {
  title: "Top 1000",
  description: "Generated by create next app",
};

// Корневой layout для приложения
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={gilroy.variable}>{children}</body>
    </html>
  );
}
